# Generated by Django 3.1.2 on 2020-11-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('Cedula', models.CharField(max_length=200)),
                ('Fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(max_length=200, verbose_name='Género')),
                ('Ciudad', models.CharField(default='Pereira', max_length=200, verbose_name='Ciudad de residencia')),
                ('suscripcion', models.BooleanField(blank=True, default=True, null=True, verbose_name='Suscribirme a noticias')),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
