# Generated by Django 3.1.2 on 2020-11-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20201111_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='temas_preferidos',
            field=models.IntegerField(blank=True, default=True, null=True, verbose_name='Temas de preferencia'),
        ),
    ]
