# Generated by Django 3.1.2 on 2020-11-11 07:30

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20201111_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='temas_preferidos',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Historia y Geografía', 'Historia y Geografía'), ('Narrativa', 'Narrativa'), ('Juvenil', 'Juvenil'), ('Ciencias físicas', 'Ciencias físicas'), ('Infantil', 'Infantil'), ('Ciencias Sociales y política', 'Ciencias Sociales y política'), ('Medicina y salud', 'Medicina y salud'), ('Filosofía', 'Filosofía'), ('Arquitectura', 'Arquitectura'), ('Arte', 'Arte'), ('Gastronomía', 'Gastronomía'), ('Varios', 'Varios')], max_length=157, null=True, verbose_name='Temas de preferencia'),
        ),
    ]
