# Generated by Django 3.1.2 on 2020-11-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20201111_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Ciudad',
            field=models.IntegerField(choices=[('Armenia', 'Armenia'), ('Barranquilla', 'Barranquilla'), ('Bello', 'Bello'), ('Bogotá', 'Bogotá'), ('Bucaramanga', 'Bucaramanga'), ('Cali', 'Cali'), ('Cartagena', 'Cartagena'), ('Cúcuta', 'Cúcuta'), ('Ibagué', 'Ibagué'), ('Manizales', 'Manizales'), ('Medellín', 'Medellín'), ('Montería', 'Montería'), ('Neiva', 'Neiva'), ('Cartagena', 'Cartagena'), ('Pasto', 'Pasto'), ('Pereira', 'Pereira'), ('Santa Marta', 'Santa Marta'), ('Soacha', 'Soacha'), ('Soledad', 'Soledad'), ('Valledupar', 'Valledupar'), ('Villavicencio', 'Villavicencio')], default='Pereira', max_length=200, verbose_name='Ciudad de residencia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.IntegerField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], default='Femenino', max_length=200, verbose_name='Género'),
        ),
    ]
